### PR TITLE
feat: add a way to set violation severity level in settings

### PR DESCRIPTION
**Pull request by eliecharra**
image

### CODE REVIEW

**Comment by xxpxxxxp** [comment]
That's great, thank you! Would you merge the Severity setting to same row with CPU Concurrency, to save rooms for underlying linter table. In Intellij you can open `GoLinterConfigurable.form` then drag & drop components, no need to write java code.

**Comment by eliecharra** [comment]
@xxpxxxxp Just updated the form.

You can see what it looks like on the new screenshot attached to the first message.

**Comment by yu-peng-wang** [comment]
thank you, merged, I'll publish a new version ASAP

**Comment by xxpxxxxp** [comment]
thank you, merged, I'll publish a new version ASAP

**Pull request merged**
